# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76213672c79ffac09e3ebf74eb378482f78dab2ec2efce0f935ed82ac808ea6b2d701983da80625c8f56cdbe91b173518cf14e61761971301392ca7070f216a7

test:
  secret_key_base: b40e1b998b87bd18c850e9d88ec4c98b8e9a72d53fddc2c2fc0315f0ff22987205c0c4e5beae8004553f60ca151d3c1b54e555a9973ffcb871230c17cd86fd5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
